#### error 接口

Go 语言为错误处理定义了一个标准模式，即 `error` 接口，该接口的定义非常简单：

```go
type error interface { 
    Error() string 
}
```

可以通过 `errors.New()` 方法创建 `error` 类型错误信息：

```go
func add(a, b *int) (c int, err error) {
    if (*a < 0 || *b < 0) {
        err = errors.New("只支持非负整数相加")
        return
    }
    *a *= 2
    *b *= 3
    c = *a + *b
    return
}
```

Go 语言内置的很多包还封装了很多更复杂的错误类型：

```go
type PathError struct {
    Op   string
    Path string
    Err  error    // 这是个接口类型
}
```

#### defer 语句

通过 `defer` 关键字声明兜底执行或者释放资源的语句。

```go
func ReadFile(filename string) ([]byte, error) {
    f, err := os.Open(filename)
    if err != nil {
        return nil, err
    }
    defer f.Close()

    var n int64 = bytes.MinRead

    if fi, err := f.Stat(); err == nil {
        if size := fi.Size() + bytes.MinRead; size > n {
            n = size
        }
    }
    return readAll(f, n)
}
```

如果一条语句干不完清理的工作，也可以在 `defer` 后加一个匿名函数来执行对应的兜底逻辑：

```go
defer func() { 
    //  执行复杂的清理工作... 
} ()
```

一个函数/方法中可以存在多个 `defer` 语句，`defer` 语句的调用顺序遵循先进后出的原则，即最后一个 `defer` 语句将最先被执行，相当于「栈」结构，如果在循环语句中包含了 `defer` 语句，则对应的 `defer` 语句执行顺序依然符合先进后出的规则。

#### panic 和 recover

 Go 语言通过 [error 接口](https://xueyuanjun.com/post/19871.html)统一进行错误处理，但这些错误都是我们在编写代码时就已经预见并返回的，对于某些运行时错误，比如数组越界、除数为0、空指针引用，Go 语言会抛出 panic（恐慌）

可以显示抛出：

```go
func panic(v interface{})
```

可以通过 `recover()` 函数对 panic 进行捕获和处理，从而避免程序崩溃然后直接退出，panic 的捕获和其他代码的恢复执行需要放到 defer 语句中完成。

```go
package main

import (
    "fmt"
)

func divide() {
    defer func() {
        if err := recover(); err != nil {
            fmt.Printf("Runtime panic caught: %v\n", err)
        }
    }()

    var i = 1
    var j = 0
    k := i / j
    fmt.Printf("%d / %d = %d\n", i, j, k)
}

func main() {
    divide()
    fmt.Println("divide方法调用完毕，回到main函数")
}
```

